CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY UUID,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS businessProfile(
    id SERIAL PRIMARY KEY UUID,
    user_id INT REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    business_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    business_address VARCHAR(255),
    logo_url VARCHAR(255),
    default_currency VARCHAR(10) DEFAULT 'KSH',
    phone_number VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client(
    id SERIAL PRIMARY KEY UUID,
    user_id INT REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    client_name VARCHAR(100) NOT NULL,
    email VARCHAR(100)  NOT NULL,
    phone_number VARCHAR(20),
    client_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote(
    id SERIAL PRIMARY KEY UUID,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    client_id INT REFERENCES client(id) ON DELETE CASCADE,
    quote_number VARCHAR(50) UNIQUE NOT NULL,
    issued_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMP,
    currency VARCHAR(10) DEFAULT 'KSH',
    subtotal NUMERIC(14,2) NOT NULL,
    tax_rate NUMERIC(14,2) DEFAULT 0,
    tax_amount NUMERIC(14,2) DEFAULT 0,
    discount_rate NUMERIC(14,2) DEFAULT 0,
    discount_amount NUMERIC(14,2) DEFAULT 0,
    total NUMERIC(14,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'draft',
    notes TEXT,
    terms TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_item(
    id SERIAL PRIMARY KEY UUID,
    quote_id INT REFERENCES quote(id) ON DELETE CASCADE,
    description VARCHAR(255) NOT NULL,
    quantity NUMERIC(14,2) NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL,
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoice(
    id SERIAL PRIMARY KEY UUID,
    user_id  REFERENCES users(id) UUID ON DELETE CASCADE,
    client_id INT REFERENCES client(id) UUID ON DELETE CASCADE,
    source_quote_id INT UUID REFERENCES UNIQUE quote(id) ON DELETE SET NULL,
    invoice_number VARCHAR(50) UNIQUE NOT NULL,
    issued_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMP,
    currency VARCHAR(10) DEFAULT 'KSH',
    subtotal NUMERIC(14,2) NOT NULL,
    tax_rate NUMERIC(14,2) DEFAULT 0,
    tax_amount NUMERIC(14,2) DEFAULT 0,
    discount_rate NUMERIC(14,2) DEFAULT 0,
    discount_amount NUMERIC(14,2) DEFAULT 0,
    total NUMERIC(14,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'draft',
    notes TEXT,
    terms TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoice_item(
    id SERIAL PRIMARY KEY UUID,
    invoice_id INT REFERENCES invoice(id) ON DELETE CASCADE,
    description VARCHAR(255) NOT NULL,
    quantity NUMERIC(14,2) NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL,
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipt(
    id SERIAL PRIMARY KEY UUID,
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    client_id INT REFERENCES client(id) ON DELETE CASCADE,
    source_invoice_id INT REFERENCES invoice(id) ON DELETE SET NULL,
    receipt_number VARCHAR(50) UNIQUE NOT NULL,
    issued_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMP,
    currency VARCHAR(10) DEFAULT 'KSH',
    subtotal NUMERIC(14,2) NOT NULL,
    tax_rate NUMERIC(14,2) DEFAULT 0,
    tax_amount NUMERIC(14,2) DEFAULT 0,
    discount_rate NUMERIC(14,2) DEFAULT 0,
    discount_amount NUMERIC(14,2) DEFAULT 0,
    total NUMERIC(14,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'draft',
    notes TEXT,
    terms TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receipt_item(
    id SERIAL PRIMARY KEY UUID,
    receipt_id INT REFERENCES receipt(id) ON DELETE CASCADE,
    description VARCHAR(255) NOT NULL,
    quantity NUMERIC(14,2) NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL,
    position INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);






