import os
import io
import tempfile
import unittest
from datetime import timedelta
from pathlib import Path
from unittest.mock import patch
from uuid import UUID, uuid4

import psycopg
from dotenv import load_dotenv
from psycopg import sql

from app.common.database import DatabaseConfigurationError, DatabaseSettings, connect_database
from app.common.migrations import MIGRATIONS_DIRECTORY, MigrationError, apply_migrations
from app.db import main


class DatabaseSettingsTests(unittest.TestCase):
    primary = "postgresql://user:secret@localhost:5432/billing"
    test_url = "postgresql://user:secret@localhost:5432/billing_test"

    def test_explicit_test_database_required(self):
        for target in ("", self.primary, self.primary + "_other"):
            with self.subTest(target=target), self.assertRaises(DatabaseConfigurationError):
                DatabaseSettings(self.primary, target).connection_url(test=True)
        self.assertEqual(DatabaseSettings(self.primary, self.test_url).connection_url(test=True), self.test_url)

    def test_invalid_urls_do_not_expose_credentials(self):
        for value in ("", "sqlite:///file", "postgresql://user:secret@bad@localhost/db", "postgresql://user:secret#@localhost/db", "postgresql://localhost"):
            with self.subTest(value=value):
                with self.assertRaises(DatabaseConfigurationError) as error:
                    DatabaseSettings(value).connection_url()
                self.assertNotIn("secret", str(error.exception))

    def test_encoded_password_and_secret_free_repr(self):
        url = "postgresql://user:secret%40%23@localhost/billing"
        settings = DatabaseSettings(url, self.test_url)
        self.assertEqual(settings.connection_url(), url)
        self.assertNotIn("secret", repr(settings))

    def test_environment_settings(self):
        with patch.dict(os.environ, {"DATABASE_URL": self.primary, "TEST_DATABASE_URL": self.test_url}, clear=True):
            self.assertEqual(DatabaseSettings.from_environment().connection_url(test=True), self.test_url)

    def test_command_failure_does_not_leak_driver_details(self):
        output = io.StringIO()
        with patch("sys.argv", ["app.db", "check"]), patch("sys.stderr", output), \
                patch("app.db.load_dotenv"), \
                patch("app.db.connect_database", side_effect=psycopg.OperationalError("secret credential")):
            self.assertEqual(main(), 1)
        self.assertIn("Database operation failed", output.getvalue())
        self.assertNotIn("secret credential", output.getvalue())


class PostgreSQLMigrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        load_dotenv(Path(__file__).resolve().parents[1] / ".env", override=False)
        if not os.getenv("TEST_DATABASE_URL"):
            raise unittest.SkipTest("Set TEST_DATABASE_URL to run PostgreSQL integration tests")
        cls.settings = DatabaseSettings.from_environment()
        # Never fall back to the application database, even for invalid test settings.
        cls.settings.connection_url(test=True)

    def setUp(self):
        self.connection = connect_database(self.settings, test=True)
        self.addCleanup(self.connection.close)
        self.schema = "migration_test_" + uuid4().hex
        self.connection.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(self.schema)))
        self.addCleanup(self.drop_test_schema)
        self.connection.execute(sql.SQL("SET search_path TO {}").format(sql.Identifier(self.schema)))

    def drop_test_schema(self):
        # This name was generated by this test in the explicitly separate test DB.
        self.connection.execute(sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(self.schema)))

    def test_fresh_migration_and_repeat(self):
        self.assertEqual(apply_migrations(self.connection), ["001_initial.sql"])
        self.assertEqual(apply_migrations(self.connection), [])
        tables = self.connection.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_schema = %s", (self.schema,)
        ).fetchall()
        self.assertEqual({row[0] for row in tables}, {
            "users", "business_profiles", "clients", "quotes", "quote_items", "invoices",
            "invoice_items", "receipts", "receipt_items", "schema_migrations",
        })
        self.assertEqual(self.connection.execute("SHOW timezone").fetchone()[0], "UTC")
        self.assertEqual(self.connection.execute(
            "SELECT numeric_precision, numeric_scale FROM information_schema.columns "
            "WHERE table_schema = %s AND table_name = 'quote_items' AND column_name = 'quantity'",
            (self.schema,),
        ).fetchone(), (12, 3))

    def test_uuid_defaults_and_utc_update_trigger(self):
        apply_migrations(self.connection)
        user_id, created, updated = self.connection.execute(
            "INSERT INTO users (name, email, password_hash) VALUES ('Test', 'test@example.com', 'test-only') "
            "RETURNING id, created_at, updated_at"
        ).fetchone()
        self.assertIsInstance(user_id, UUID)
        self.assertEqual(created.utcoffset(), timedelta(0))
        self.assertEqual(created, updated)
        changed_created, changed_updated = self.connection.execute(
            "UPDATE users SET name = 'Changed' WHERE id = %s RETURNING created_at, updated_at", (user_id,)
        ).fetchone()
        self.assertEqual(changed_created, created)
        self.assertGreaterEqual(changed_updated, updated)

    def test_pending_batch_failure_rolls_back_schema_and_history(self):
        apply_migrations(self.connection)
        with tempfile.TemporaryDirectory() as temp:
            directory = Path(temp)
            initial = (MIGRATIONS_DIRECTORY / "001_initial.sql").read_text(encoding="utf-8")
            (directory / "001_initial.sql").write_text(initial, encoding="utf-8")
            (directory / "002_probe.sql").write_text("CREATE TABLE rollback_probe (id INTEGER);", encoding="utf-8")
            broken = directory / "003_failure.sql"
            broken.write_text("SELECT * FROM missing_migration_table;", encoding="utf-8")
            with self.assertRaises(psycopg.errors.UndefinedTable):
                apply_migrations(self.connection, directory)
            self.assertIsNone(self.connection.execute("SELECT to_regclass('rollback_probe')").fetchone()[0])
            self.assertEqual(self.connection.execute("SELECT count(*) FROM schema_migrations").fetchone()[0], 1)
            broken.write_text("CREATE TABLE retry_probe (id INTEGER);", encoding="utf-8")
            self.assertEqual(apply_migrations(self.connection, directory), ["002_probe.sql", "003_failure.sql"])

    def test_applied_migration_edits_are_rejected(self):
        apply_migrations(self.connection)
        with tempfile.TemporaryDirectory() as temp:
            directory = Path(temp)
            (directory / "001_initial.sql").write_text("SELECT 1;", encoding="utf-8")
            with self.assertRaises(MigrationError):
                apply_migrations(self.connection, directory)
        self.assertEqual(self.connection.execute("SELECT count(*) FROM schema_migrations").fetchone()[0], 1)
